"""change rating_stars datatype

Revision ID: 93001aab29d9
Revises: 
Create Date: 2026-05-28 12:37:26.345663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93001aab29d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating_stars',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=2, scale=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating_stars',
               existing_type=sa.Numeric(precision=2, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
